"""formatter 모듈 테스트"""

import pytest

from kr_code_reviewer.formatter import (
    format_review_compact,
    format_review_github_comment,
    format_review_markdown,
    _get_score_grade,
)
from kr_code_reviewer.reviewer import ReviewComment, ReviewResult


# ============================================================
# _get_score_grade 테스트
# ============================================================

class TestGetScoreGrade:

    def test_excellent(self):
        assert "훌륭" in _get_score_grade(9)
        assert "훌륭" in _get_score_grade(10)

    def test_good(self):
        assert "양호" in _get_score_grade(7)
        assert "양호" in _get_score_grade(8)

    def test_needs_improvement(self):
        assert "개선" in _get_score_grade(5)
        assert "개선" in _get_score_grade(6)

    def test_critical(self):
        assert "심각" in _get_score_grade(1)
        assert "심각" in _get_score_grade(4)

    def test_zero(self):
        assert "평가 불가" in _get_score_grade(0)


# ============================================================
# 포매터 출력 테스트
# ============================================================

@pytest.fixture
def sample_result():
    return ReviewResult(
        summary="테스트 요약입니다.",
        overall_score=7,
        diff_summary="2개 파일 변경, +10 추가, -3 삭제",
        comments=[
            ReviewComment(
                file_path="main.py",
                line_range="L10-L15",
                severity="warning",
                category="bug",
                comment="변수가 초기화되지 않았습니다.",
                suggestion="x = 0",
            ),
            ReviewComment(
                file_path="utils.py",
                line_range="L5",
                severity="suggestion",
                category="readability",
                comment="함수 이름이 모호합니다.",
                suggestion="",
            ),
        ],
    )


@pytest.fixture
def empty_result():
    return ReviewResult(
        summary="변경사항이 없습니다.",
        overall_score=10,
    )


class TestFormatReviewMarkdown:

    def test_contains_header(self, sample_result):
        output = format_review_markdown(sample_result)
        assert "코드 리뷰 결과" in output

    def test_contains_score(self, sample_result):
        output = format_review_markdown(sample_result)
        assert "7/10" in output

    def test_contains_summary(self, sample_result):
        output = format_review_markdown(sample_result)
        assert "테스트 요약" in output

    def test_contains_comments(self, sample_result):
        output = format_review_markdown(sample_result)
        assert "main.py" in output
        assert "초기화" in output

    def test_empty_comments(self, empty_result):
        output = format_review_markdown(empty_result)
        assert "특이사항 없음" in output


class TestFormatReviewCompact:

    def test_contains_score(self, sample_result):
        output = format_review_compact(sample_result)
        assert "7/10" in output

    def test_contains_file_path(self, sample_result):
        output = format_review_compact(sample_result)
        assert "main.py" in output


class TestFormatReviewGithubComment:

    def test_contains_header(self, sample_result):
        output = format_review_github_comment(sample_result)
        assert "KR Code Reviewer" in output

    def test_contains_details_tag(self, sample_result):
        output = format_review_github_comment(sample_result)
        assert "<details>" in output

    def test_contains_footer(self, sample_result):
        output = format_review_github_comment(sample_result)
        assert "Generated by" in output